### ISSUE TITLE
missing loot tables for block. blocks wont drop on destroy

### ISSUE THREAD

**Issue by Linguardium** [franiscoder/TacoCraft#1]
kids found that the Comal doesnt drop when destroyed. 
looks like you may be missing the loot tables for the blocks 
you may also want to check inventory on destroy to drop the item from the inventory so they arent lost.

**Comment by frqnny** [comment]
oh no

**Comment by frqnny** [comment]
sucks that you have to write a loot table for each block, should be a method imo

**Comment by franiscoder** [comment]
Fixed, a new build will come out soon when curseforge approves it. Thank you!

**Comment by frqnny** [comment]
Fixed, a new build will come out soon when curseforge approves it. Thank you!
