### ISSUE TITLE
[1.3.1]hoppers send items to comal which appears to delete them

### ISSUE THREAD

**Issue by aofsupporter** [franiscoder/TacoCraft#11]
A vanilla hopper can send tortilla dough into the comal, which implies some sort of inventory, but the item never makes it onto the comal visually the way manually placing one does.  Breaking the comal does not return the missing items.

**Comment by frqnny** [comment]
That's weird. I'll try to fix this in 1.16.2. But there is no inventory, technecally, i just really just make it a boolean instead of the patch job i did.
