### ISSUE TITLE
Compostable Corn Kernels?

### ISSUE THREAD

**Issue by Docteh** [franiscoder/TacoCraft#13]
Hi, I was playing AOF3 (2.0.2) last night and one thing I've noticed is that the corn seeds aren't able to be thrown into the composter. Is this intended? I'd like to be able to compost extra seeds. Or maybe cook them somehow. But maybe random corn seeds found on the ground are not a good idea to consume eat....

**Comment by frqnny** [comment]
Good Idea.

**Comment by frqnny** [comment]
Added in Dev- maybe released in 1.5.0+mc.1.16.3
