### ISSUE TITLE
Taco Trader crash in Multiplayer

### ISSUE THREAD

**Issue by SammyMcBlu** [franiscoder/TacoCraft#2]
In LAN multiplayer the game crashes for the players when the Taco Trader appears. However, I don't crash as I am server, only the other players. When I kill the trader they can join again without crashing. Here is a crash report from one of them:

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 4/25/20 11:28 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
at mod.linguardium.tradesmen.entities.TradesmenRenderer.getTexture(TradesmenRenderer.java:17)
at mod.linguardium.tradesmen.entities.TradesmenRenderer.method_3931(TradesmenRenderer.java:8)
at net.minecraft.class_922.method_24302(class_922.java:149)
at net.minecraft.class_922.method_4054(class_922.java:130)
at net.minecraft.class_927.method_4072(class_927.java:43)
at net.minecraft.class_927.method_3936(class_927.java:18)
at net.minecraft.class_898.method_3954(class_898.java:256)
at net.minecraft.class_761.method_22977(class_761.java:1353)
at net.minecraft.class_761.method_22710(class_761.java:1167)
at net.minecraft.class_757.method_3188(class_757.java:718)
at net.minecraft.class_757.method_3192(class_757.java:543)
at net.minecraft.class_310.method_1523(class_310.java:989)
at net.minecraft.class_310.method_1514(class_310.java:619)
at net.minecraft.client.main.Main.main(Main.java:204)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
at mod.linguardium.tradesmen.entities.TradesmenRenderer.getTexture(TradesmenRenderer.java:17)
at mod.linguardium.tradesmen.entities.TradesmenRenderer.method_3931(TradesmenRenderer.java:8)
at net.minecraft.class_922.method_24302(class_922.java:149)
at net.minecraft.class_922.method_4054(class_922.java:130)
at net.minecraft.class_927.method_4072(class_927.java:43)
at net.minecraft.class_927.method_3936(class_927.java:18)

-- Entity being rendered --
Details:
Entity Type: tradesmen:tradesmen_seller (mod.linguardium.tradesmen.entities.TradesmenEntity)
Entity ID: 67158
Entity Name: ~~ERROR~~ NullPointerException: null
Entity's Exact location: 146.50, 69.00, -118.50
Entity's Block location: World: (146,69,-119), Chunk: (at 2,4,9 in 9,-8; contains blocks 144,0,-128 to 159,255,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Entity's Momentum: 0.00, 0.00, 0.00
Entity's Passengers: []
Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
Assigned renderer: mod.linguardium.tradesmen.entities.TradesmenRenderer@6b71002
Location: -0.40,3.38,-15.84 - World: (-1,3,-16), Chunk: (at 15,0,0 in -1,-1; contains blocks -16,0,-16 to -1,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
Rotation: -157.5
Delta: 0.20002794
Stacktrace:
at net.minecraft.class_898.method_3954(class_898.java:256)
at net.minecraft.class_761.method_22977(class_761.java:1353)
at net.minecraft.class_761.method_22710(class_761.java:1167)
at net.minecraft.class_757.method_3188(class_757.java:718)

-- Affected level --
Details:
All players: 3 total; [class_746['KTimeKP'/64303, l='MpServer', x=146.99, y=64.00, z=-102.53], class_745['mrrc13'/61743, l='MpServer', x=156.96, y=64.00, z=-111.40], class_745['MMU1230'/64674, l='MpServer', x=146.32, y=65.00, z=-116.76]]
Chunk stats: Client Chunk Cache: 841, 600
Level dimension: minecraft:overworld
Level name: MpServer
Level seed: -4731882207853012198
Level generator: ID 00 - default, ver 1. Features enabled: false
Level generator options: {}
Level spawn location: World: (139,63,-112), Chunk: (at 11,3,0 in 8,-7; contains blocks 128,0,-112 to 143,255,-97), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Level time: 2883176 game time, 4690757 day time
Known server brands:
Level was modded: false
Level storage version: 0x00000 - Unknown?
Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Server brand: fabric
Server type: Non-integrated multiplayer server
Stacktrace:
at net.minecraft.class_638.method_8538(class_638.java:450)
at net.minecraft.class_310.method_1587(class_310.java:1921)
at net.minecraft.class_310.method_1514(class_310.java:634)
at net.minecraft.client.main.Main.main(Main.java:204)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
Minecraft Version: 1.15.2
Minecraft Version ID: 1.15.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 1416351232 bytes (1350 MB) / 2046820352 bytes (1952 MB) up to 2147483648 bytes (2048 MB)
CPUs: 12
JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
Fabric Mods:
adorn: Adorn 1.8.4+1.15.2
amethystmod: Amethyst Mod 1.2.1
atmosfera: Atmosfera 1.2.0
autoconfig1u: Auto Config v1 Updated 2.0.1
bambootweaks: Bamboo Tweaks 1.1.4+fabric-1.15.2
beebetter: Bee Better 1.6.0
bettersleeping: Better Sleeping 0.3.0
bowinfinityfix: Bow Infinity Fix rv8
chickenfeathers: Chicken Feathers 1.2.0
chunkactivator: Chunk Activator 2.0.0+mc1.15.2
clipboards: Clipboards 1.0.0+1.15.2
cloth: Cloth Events 1.1.0
cloth-basic-math: Cloth Basic Math 0.4.1
cloth-config2: Cloth Config v2 2.13.2
coloredcampfire: Colorful Campfire Smoke 1.1.1
com_moandjiezana_toml_toml4j: toml4j 0.7.2
composableautomation: Composable Automation 0.8.0+mc1.15.2
corail_woodcutter: Corail Woodcutter 1.0.0
corailaddon: Corail Woodcutter Addon Mod 1.0.4
couplings: Couplings 1.3.1
fabric: Fabric API 0.5.1+build.294-1.15
fabric-api-base: Fabric API Base 0.1.2+28f8190f42
fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
fabric-commands-v0: Fabric Commands (v0) 0.1.2+b7f9825d0c
fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+b7f9825d0c
fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+ec40b2e10c
fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
fabric-language-kotlin: Fabric Language Kotlin 1.3.61+build.1
fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.1+b7f9825d0c
fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
fabric-networking-v0: Fabric Networking (v0) 0.1.8+9421522de7
fabric-object-builders-v0: Fabric Object Builders (v0) 0.1.3+e4c9a9c30c
fabric-particles-v1: fabric-particles-v1 0.1.1+dfdb52d60c
fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
fabric-rendering-v1: Fabric Rendering (v1) 0.1.0+534104900c
fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
fabricloader: Fabric Loader 0.8.2+build.194
fairenchanting: FairEnchanting 1.1.1
fishtraps: Fish Traps 1.0.7
flax: Flax 1.1.1
fleshz: FleshZ 1.1.0
gravestones: Gravestones 1.2.0
horsestatsvanilla: Horse Stats Vanilla 1.0.5
jankson: Jankson 2.0.1+j1.2.0
jumpoverfences: JumpOverFences 1.15-0.0.1
libcd: LibCapableData 2.3.0+1.15.2
libgui: LibGui 1.8.1+1.15.2
lightoverlay: Light Overlay 4.1-unstable.201912010451
lithium: Lithium 0.4.6
llamasteeds: Llama Steeds 2020.1.10
mcf-reap: MaxVar reap for fabric 1.3.0
minecraft: Minecraft 1.15.2
ml3api: ML3API 1.3.1
mm: Manningham Mills 2.0
modid: Floriculture 1.0.1
modmenu: Mod Menu 1.10.2+build.32
more_gems: More Gems 1.0.2
nbtcrafting: NBT Crafting 1.2.15+1.15.1
orderly: Orderly 1.2.0+build.1-1.15
org_jetbrains_annotations: annotations 18.0.0
org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.61
org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.61
org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.61
org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.61
org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.3
org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.3
roughlyenoughitems: Roughly Enough Items 3.6.12
sandwichable: Sandwichable 1.0.2
shulkerboxtooltip: Shulker Box Tootip 1.4.4+1.15.0
sifter: Sifter & Friends 1.1.0
smith_and_fletch: Smith And Fletch 1.0.0
sneakthroughberries: Sneak Through Berries 1.0.1
spinnery: Spinnery 2.0.0+fabric-20w06a
strongandfairanvils: Strong and Fair Anvils 0.3.0+1.15
stuffz: StuffZ 1.8.0
sweettooth: Sweet Tooth 1.1.2
tacocraft: TacoCraft 1.2.1
tradesmen: Wandering Tradesmen 1.1.1
trapexpansion: Trap Expansion 1.3.1
trees-do-not-float: Trees Do Not Float 1.8.69
vanilla-toolsets: Vanilla Toolsets 1.2.2
Launched Version: fabric-loader-0.8.2+build.194-1.15.2
Backend library: LWJGL version 3.2.2 build 10
Backend API: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 26.20.100.7637, Intel
GL Caps: Using framebuffer using OpenGL 3.0
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fabric'
Type: Client (map_client.txt)
Resource Packs: vanilla, file/atmosfera-sounds-1.2.0.zip
Current Language: English (US)
CPU: 12x Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz

**Comment by frqnny** [comment]
Thank you, I will report the bug right now.

**Comment by Linguardium** [comment]
Can i get a full log from both the server and client? 
logs just needs to show just before and after client connection since we are looking for connection messages from player login.
Pretty sure i fixed this already. I want to see if the server is sending the Tradesmen to the client and if the client is receiving them

**Comment by frqnny** [comment]
Hey, Sammy, can you try replicating with this jar? Make sure everyone has it in the server and client. 
https://github.com/franiscoder/TacoCraft/releases/tag/1.2.2
I just tested it and I did not appear to be able to recreate it.

**Comment by SammyMcBlu** [comment]
Ok will do. It will have to be a bit later today when I can get back to you as the other players are not available right now.

**Comment by frqnny** [comment]
Open a new issue if the issue persists on the new version, but I am going to close this issue.
