### ISSUE TITLE
Crashing in my 1.18.2 modpack

### ISSUE THREAD

**Issue by TheButterbrotMan** [franiscoder/TacoCraft#23]
https://bytebin.lucko.me/93vXlxbmnf

**Comment by JCastaneda-Dev** [comment]
I don't think this mod is for 1.18.2

**Comment by TheButterbrotMan** [comment]
Its not hardcoded to 1.18.1, so i assume they are willing to fix it. If it doesnt work on 1.18.2.

**Comment by JCastaneda-Dev** [comment]
The mod is not being worked on at the moment due to irl reasons from the developer
