### ISSUE TITLE
Taco trader still crashes in multiplayer LAN

### ISSUE THREAD

**Issue by CodexDraco** [franiscoder/TacoCraft#3]
Using version 1.2.2. Clients crash but the server host keeps working.

Crash report:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 5/17/20 8:31 PM
Description: Rendering entity in world

java.lang.NullPointerException: Rendering entity in world
	at mod.linguardium.tradesmen.entities.TradesmenRenderer.getTexture(TradesmenRenderer.java:17)
	at mod.linguardium.tradesmen.entities.TradesmenRenderer.method_3931(TradesmenRenderer.java:8)
	at net.minecraft.class_922.method_24302(class_922.java:149)
	at net.minecraft.class_922.method_4054(class_922.java:130)
	at net.minecraft.class_927.method_4072(class_927.java:43)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:256)
	at net.minecraft.class_761.method_22977(class_761.java:1353)
	at net.minecraft.class_761.method_22710(class_761.java:1167)
	at net.minecraft.class_757.method_3188(class_757.java:718)
	at net.minecraft.class_757.method_3192(class_757.java:543)
	at net.minecraft.class_310.method_1523(class_310.java:989)
	at net.minecraft.class_310.method_1514(class_310.java:619)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mod.linguardium.tradesmen.entities.TradesmenRenderer.getTexture(TradesmenRenderer.java:17)
	at mod.linguardium.tradesmen.entities.TradesmenRenderer.method_3931(TradesmenRenderer.java:8)
	at net.minecraft.class_922.method_24302(class_922.java:149)
	at net.minecraft.class_922.method_4054(class_922.java:130)
	at net.minecraft.class_927.method_4072(class_927.java:43)
	at net.minecraft.class_927.method_3936(class_927.java:18)

-- Entity being rendered --
Details:
	Entity Type: tradesmen:tradesmen_seller (mod.linguardium.tradesmen.entities.TradesmenEntity)
	Entity ID: 138719
	Entity Name: ~~ERROR~~ NullPointerException: null
	Entity's Exact location: 253.83, 67.00, 132.84
	Entity's Block location: World: (253,67,132), Chunk: (at 13,4,4 in 15,8; contains blocks 240,0,128 to 255,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: mod.linguardium.tradesmen.entities.TradesmenRenderer@79fa4eb2
	Location: 3.87,-2.62,15.91 - World: (3,-3,15), Chunk: (at 3,-1,15 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 135.0
	Delta: 0.6998218
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:256)
	at net.minecraft.class_761.method_22977(class_761.java:1353)
	at net.minecraft.class_761.method_22710(class_761.java:1167)
	at net.minecraft.class_757.method_3188(class_757.java:718)

-- Affected level --
Details:
	All players: 3 total; [class_746['CodexDraco'/4034, l='MpServer', x=249.93, y=68.00, z=116.99], class_745['daus_kaus'/288, l='MpServer', x=236.55, y=63.19, z=110.09], class_745['Lalo'/134652, l='MpServer', x=232.85, y=63.00, z=100.48]]
	Chunk stats: Client Chunk Cache: 1089, 784
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: 4002729046035438607
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (240,68,128), Chunk: (at 0,4,0 in 15,8; contains blocks 240,0,128 to 255,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 685816 game time, 773104 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:450)
	at net.minecraft.class_310.method_1587(class_310.java:1921)
	at net.minecraft.class_310.method_1514(class_310.java:634)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1628919776 bytes (1553 MB) / 3618635776 bytes (3451 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 4
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx8192m
	Fabric Mods: 
		adorn: Adorn 1.8.4+1.15.2
		amecs: Amecs 1.2.9+1.15-pre5
		appleskin: AppleSkin 1.0.8
		autoconfig1u: Auto Config v1 Updated 2.0.1
		beebetter: Bee Better 1.6.0
		beecompatible: Bee Compatible 2.0.0+1.15.1
		beeproductive: Bee Productive 1.0.2+1.15.1
		better_wither_skeletons: Better Wither Skeletons 1.0.0
		betternether: Better Nether 2.7.3
		betterthanmending: BetterThanMending 1.1.1
		blockus: Blockus 1.5.2.1-1.15.2
		blue_endless_jankson: jankson +
		bunch-o-trinkets: Bunch O' Trinkets 1.0.0
		campanion: Campanion 1.0.9+custom
		cardinal-components-base: Cardinal Components API 2.1.0
		cardinal-components-entity: Cardinal Components API 2.1.0
		cavebiomes: Cave Biomes 0.2.1
		chunkactivator: Chunk Activator 2.0.0+mc1.15.2
		claybucket: Clay Bucket 1.0.0
		cleardespawn: Clear Despawn 1.0.4
		cloth: Cloth Events 1.2.0
		cloth-basic-math: Cloth Basic Math 0.5.0
		cloth-config2: Cloth Config v2 2.13.4
		compressedblocks: Compressed Blocks 0.3
		convth: Convenient Things 0.6.0
		couplings: Couplings 1.3.1
		crafthacks: Craft Hacks 1.0.2
		creeperspores: Creeper Spores 1.3.7
		diggusmaximus: Diggus Maximus 1.2.9
		extraalchemy: Extra Alchemy 1.0.1
		fabric: Fabric API 0.10.8+build.310-1.15
		fabric-api-base: Fabric API Base 0.1.2+b7f9825d0c
		fabric-biomes-v1: Fabric Biomes (v1) 0.1.5+3b05f68e0c
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea890c
		fabric-climbable-api-v1: Fabric Climbable API (v1) 1.0.0+6ffe71e20c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.2+2aebb7ff0c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+2e0c4ff50c
		fabric-containers-v0: Fabric Containers (v0) 0.1.3+b7f9825d0c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.3+b7f9825d0c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d0c
		fabric-dimensions-v1: fabric-dimensions-v1 0.3.0+2ad156310c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.0+fac69e320c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.2+003643510c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.1.6+045efb460c
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.1.1+dfdb52d60c
		fabric-language-kotlin: Fabric Language Kotlin 1.3.61+build.1
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.5+e08a73050c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+ec951ea40c
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d60c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.3+e08a73050c
		fabric-networking-v0: Fabric Networking (v0) 0.1.7+12515ed90c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.1.0+3e5587510c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.5.1+3e5587510c
		fabric-particles-v1: fabric-particles-v1 0.1.2+ad2f81bd0c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.2.6+f3d8141b0c
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.10+f08b61330c
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.2.23+9290e2ed0c
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a600c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d0c
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.6+12515ed90c
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104900c
		fabric-rendering-v1: Fabric Rendering (v1) 1.0.0+2a034f0a0c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.1.10+06c939b30c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.1.3+abd915800c
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+821cdba70c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.0+3e5587510c
		fabricloader: Fabric Loader 0.8.3+build.196
		fairenchanting: FairEnchanting 1.1.2
		fishtraps: Fish Traps 1.0.7
		flax: Flax 1.1.1
		gbfabrictools: GBfabrictools 1.2.1.1.15
		godown: Go Down 0.2.0+1.15
		grass_kiss: Grass Kiss 0.2.2
		harvest: Harvest 1.0.4
		illuminations: Illuminations 0.6
		improved-stations: Improved Stations 1.2.4
		inventoryprofiles: Inventory Profiles 0.2.0
		jankson: Jankson 2.0.1+j1.2.0
		jumplessstep: Jumpless Step 0.1.0+1.15
		jumpoverfences: JumpOverFences 1.16-snapshot-0.0.2
		kyrptconfig: Kytpt Config 1.0.0
		libblockattributes_core: LibBlockAttributes (Core) 0.5.0
		libblockattributes_items: LibBlockAttributes (Items) 0.5.0
		libcd: LibCapableData 2.3.0+1.15.2
		libgui: LibGui 1.8.2+1.15.2
		lightoverlay: Light Overlay 4.6.1
		mcf-easyfeed: Easy Feed and Breed 1.2.0
		me_shedaniel_cloth_basic-math: basic-math 0.3.0
		minecraft: Minecraft 1.15.2
		ml3api: ML3API 1.3.1
		mobz: MobZ 2.2.1
		modmenu: Mod Menu 1.10.2+build.32
		mousewheelie: Mouse Wheelie 1.4.5+mc1.15.2-pre1
		orderly: Orderly 1.2.1+build.4-1.15
		org_jetbrains_annotations: annotations 18.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.61
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.61
		org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.3
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.3
		oysters: Oysters fabric-0.1.5-1.15.2
		reach-entity-attributes: Reach Entity Attribute 1.0.0
		reborncore: Reborn Core 4.2.9+build.115
		roughlyenoughitems: Roughly Enough Items 3.6.14
		sandwichable: Sandwichable 1.0.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stockpile: Stockpile 1.1.3+1.15.1
		strongandfairanvils: Strong and Fair Anvils 0.3.0+1.15
		sweettooth: Sweet Tooth 1.1.2
		tacocraft: TacoCraft 1.2.2
		team_reborn_energy: Energy 0.1.0
		techreborn: Tech Reborn 3.3.11+build.224
		terraform: Terraform 1.5.5+build.39
		terrestria: Terrestria 1.2.1+build.29
		the_loved_ones: The Loved Ones 1.0.0-1.15.2
		thehallow: The Hallow 1.1.4-beta+1.15.2
		tradesmen: Wandering Tradesmen 1.1.1
		traverse: Traverse 2.1.14+build.37
		trees-do-not-float: Trees Do Not Float 1.8.69
		trinkets: Trinkets 2.4.2
		tweed: Tweed API 2.2.8
		vanilla-hammers: Vanilla Hammers 1.7.0
		voxelmap: VoxelMap 1.9.18.1
		waila: Hwyla 1.9.22
		worldtime: WorldTime (and Location) 1.15-fabric0.4.23-1.0
		worldtraveler: World Traveler 1.0.5
		yet_another_gravestone_mod: Yet Another Gravestone Mod 1.2.0
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Español (México)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz

**Comment by frqnny** [comment]
Looks like for some reason it kept the old tradesmen lib without the fix, weird.

**Comment by frqnny** [comment]
I really apologize for this.

**Comment by frqnny** [comment]
I can't replicate the issue really, I'm running a server fine, what were you doing when this happened??

**Comment by frqnny** [comment]
Can you pass me the latest.log from the server too?

**Comment by frqnny** [comment]
Can you try with this build, on everyone please? 
https://github.com/franiscoder/TacoCraft/releases/tag/1.2.3%2Bbeta.1

**Comment by Linguardium** [comment]
anyone with this issue, we really do need the log data from just before and just after player connection on both the server and client. This lets us see what communication is happening from client and server to ensure the correct data is being sent.

**Comment by CodexDraco** [comment]
Ok, I'll try to reproduce, is there a quick way to summon the taco trader?

**Comment by Linguardium** [comment]
in creative, you can use the trader spawner eggs

**Comment by Linguardium** [comment]
(or set the spawn time to 1200)

**Comment by CodexDraco** [comment]
I reproduced using version 1.2.2 and the 1.2.3 jar linked above. I'm attaching both sets of logs for server and client. I hope this help. Let me know if you need more information.

[server-1.2.2-latest.log](https://github.com/franiscoder/TacoCraft/files/4646733/server-1.2.2-latest.log)
[1.2.2-crash-2020-05-18_15.15.50-client.txt](https://github.com/franiscoder/TacoCraft/files/4646736/1.2.2-crash-2020-05-18_15.15.50-client.txt)
[1.2.3-crash-2020-05-18_15.21.11-client.txt](https://github.com/franiscoder/TacoCraft/files/4646737/1.2.3-crash-2020-05-18_15.21.11-client.txt)
[client-1.2.2-2020-05-18-4.log](https://github.com/franiscoder/TacoCraft/files/4646738/client-1.2.2-2020-05-18-4.log)
[client-1.2.3-latest.log](https://github.com/franiscoder/TacoCraft/files/4646739/client-1.2.3-latest.log)
[server-1.2.3-latest.log](https://github.com/franiscoder/TacoCraft/files/4646740/server-1.2.3-latest.log)

**Comment by Linguardium** [comment]
Try putting the latest wandering trader mod into your mods folders on your server and client https://github.com/Linguardium/WanderingTradesmen/releases/latest

for some reason your client is unable to load into the server or the server isnt sending data to the client (which it should be). this new release should at least let the client load in

the newer version should be showing this in the server log:
```
[09:05:15] [Server thread/INFO] (Tradesmen) [Wandering Tradesmen] Sending traders to client: Player397
[09:05:15] [Server thread/INFO] (Tradesmen) [Wandering Tradesmen] Sending Clear Trader to player Player397
[09:05:15] [Server thread/INFO] (Tradesmen) [Wandering Tradesmen] Sending Trader tradesmen:master_armorer to player Player397
```

and this in the client log
```
[09:05:21] [main/INFO] (Tradesmen) [Wandering Tradesmen] Received trader: tradesmen:master_armorer
```

This may not log without setting specific logging settings, i can enable those if you still cant load in

**Comment by CodexDraco** [comment]
> Try putting the latest wandering trader mod into your mods folders on your server and client https://github.com/Linguardium/WanderingTradesmen/releases/latest
> 
Adding this library in the mods folders did the trick! Now I can see and interact with the trader. Thank you! :)

**Comment by Linguardium** [comment]
@franiscoder sorry for the trouble, would you be able to rebuild with 1.1.3? fairly sure it was a race condition where it would try to render the trader before receiving the trader list.

**Comment by frqnny** [comment]
Done, CodexDraco go ahead and test one more time with the latest TacoCraft and it'll be done!

**Comment by CodexDraco** [comment]
I tried the 1.2.4 jar and it worked, thank you!

There's only one small issue I didn't notice yesterday it's that the trader is using the default blue color for the clothes instead of the amber color used in the hosts/singleplayer. Other than that, it works like a charm.

**Comment by Linguardium** [comment]
yeah, that is indicative of you not getting the traders sent to you by the server. Part of me thinks the server is not updated with the newer versions or for some reason it isnt working there. 

just tested latest version and server gives messages saying its sending the trader and client says it received it. not sure what else to try since i can guarantee the code is doing whats its supposed to when the latest version is on both server and client and the logs back me up.

**Comment by frqnny** [comment]
I did move the texture over to TacoCraft's own assets, so you can remove it from yours.

**Comment by frqnny** [comment]
I am going to close this issue as it appears to no longer cause a crash, and the bug is left up to Lin to try to fix.
