### ISSUE TITLE
Cannot harvest corn

### ISSUE THREAD

**Issue by DanShu15** [franiscoder/TacoCraft#4]
![2020-05-25_09 31 13](https://user-images.githubusercontent.com/40204993/82826550-99aa0580-9e6a-11ea-84e4-3985d90a55f5.png)
For some reason when we mouse over corn it's not detected. I can dig up the block beneath it but no corn or seeds drop. I spawned some seeds in to test it out and even self-planted corn cannot be harvested.
I'm using the All of Fabric mod pack for 1.15.2. I'd imagine it must be an incompatibility with another mod in the pack. I can't hit long grass for instance, but I can't figure out what mod is responsible so I can delete it lol.
Figured I'd mention that since it probably isn't actually a problem with your mod, but I wanted to report it just in case.

**Comment by frqnny** [comment]
This is weird, so you can't right click it or something?

**Comment by frqnny** [comment]
You harvest my ugly corn textures when it is ready by right clicking it. maybe something is in the way

**Comment by DanShu15** [comment]
nope, if I mouse toward it only the farmland underneath or the cobblestone wall behind it is detected. Still pretty sure it's a mod incompatibility. My servers spiraling down the drain lol gotta rebuild the mod pack today and see if it clears up. For some reason my gamerules all reset when the server restarts now, so disregard for now and I'll update when I've rebuilt the modpack :)

**Comment by frqnny** [comment]
Yeah, tell me when you fix this so I can play it and see what is happening.

**Comment by DanShu15** [comment]
Is there a way to private message on github? I'll send you the mods/config and server details to pop in and take a look while I work on it

**Comment by DanShu15** [comment]
Problem is definitely something with my mod pack, I think one of the tweaks mods. I've reinstalled it on a new modpack I'm building and it's working just fine :)

**Comment by DanShu15** [comment]
Just wanted to stop by and say the new modpack I built runs TacoCraft perfectly fine :) Had many other unrelated issues and still working on an io netty encoder error about bytes when people try to connect, but your mod is great :)
Thinking about opening up a taco stand for the server but can't pick a good name.. Taco Smell?
