### ISSUE TITLE
Disable trader

### ISSUE THREAD

**Issue by DanShu15** [franiscoder/TacoCraft#5]
Would a jar without the trader or a config option to disable the trader be possible?
I saw that it's jar in jar, could I just pull the tradeseman jar?

We have an area for shops on our server, so he's handy but easily undercut by players, and he's kindof a dick when you're by lava.
Mostly tho, I'm having connection issues and I think it might be related. Looks like a special character that shouldn't be there is messing up information sent to the client when people log in, resulting in disconnects

**Comment by DanShu15** [comment]
or is that just part of the wandering trader mod?

**Comment by frqnny** [comment]
Yeah, I guess you can just pull out the tradesman jar... Do you have the latest? I've been getting reports of this and it is very weird.

**Comment by frqnny** [comment]
1.2.4 was supposed to stop having disconnects, can you provide me the CLIENT log that gets disconnected and the Server log aswell?

1.2.4 should fix all crashes and disconnects, make sure everyone is on that version! And I can't help him being a dick and lava. is it a character names tradesmen?

**Comment by DanShu15** [comment]
Taco trader was his name I think. Fella with the bee on a leash lol he's just pushy so it's a bit dangerous when you're on a high ledge or near lava. 
Seems to run fine without the tradesman jar, no new errors or anything. For our purposes even if it had been working as intended I would prefer to be able to disable him - or go the other way and be able to supply him or otherwise employ traders to work for us. As it stands he just doesn't mesh well with how we're running our server.
Server log wise there's no errors, even on disconnect. It just says: 
https://pastebin.com/ng7ELYJt
but I can grab the latest one after next restart if I haven't got a crash. I've been trying off and on all day to crash and of course I've been able to log in without issue. So the fix seems to be you asking for a log file ;) Also oddly enough, my dad who's not very PC savvy but likes to play games is the only person who does get crashes, but it's difficult to explain what I need him to do before and after a crash to get a clear log of just the disconnect issue lol (or even to get logs at all, tbh).

I'll attach screenshots of the errors we're getting. You basically sign on, the world loads up for a split second, then you get disconnected with an error message that's usually different every time. The reason I started looking into Taco Craft was the console log does show 3 lines of information being sent to the client before the disconnect, so it seems logical that the issue could be one of the 3.
https://pastebin.com/Ezx8HDuS

woops forgot the screenshots
![2020-06-02_19 17 18](https://user-images.githubusercontent.com/40204993/83699072-58c79480-a5c0-11ea-94a1-39bfd39b448d.png)
![2020-06-02_23 31 01](https://user-images.githubusercontent.com/40204993/83699075-5bc28500-a5c0-11ea-878b-6557dcaa704c.png)

Server latest
https://pastebin.com/AAsaCXp5
Client latest
https://pastebin.com/xG1C0kTE
Another new random weird error. And the number on the bytes error changes when you get that one usually
![2020-06-03_18 03 08](https://user-images.githubusercontent.com/40204993/83700631-93333080-a5c4-11ea-8721-a90e497e202e.png)

**Comment by frqnny** [comment]
I do not believe the disconnect issues *are* about TacoCraft, I believe they are just about sending data to the client. It might be another mod.

One way to troubleshoot is for an admin to split the pack into two packs, and test each one and see which one has the error. Keep splitting the pack that has errors until you find a mod the mod.

**Comment by DanShu15** [comment]
yea I'm the poor idiot making the pack so I've tried that, but the problem is how random the reproduction is. I can go all day without a problem then it's random errors for a bit. I keep going back over the list checking for updates and dependencies but I haven't stumbled across it yet.

I was hoping to get rid of the sending trader info to client messages and see if it accomplished anything since at this point I'm going down the list 1 by 1 and giving it some time. I've got 10 friends and some family doing the testing so it's just a matter of having the time and not breaking their fun while I troubleshoot :)

Thanks a bunch for your help tho! I'll keep trying things out :) I'm sure I'll nail it at some point

**Comment by frqnny** [comment]
I am sorry if you are having issues, and I hope you solve them soon. If you continue to believe it is a TacoCraft issue, feel free to make another issue!

**Comment by DanShu15** [comment]
no worries :) I think we're good. If it WAS tacocraft then disabling the trader should've fixed it. Only other issue I've had is the Comal breaking when you try to pick it up, and if you place it on the floor you can still use it, so the oven is optional. Neither of those are big deals atm for us tho :) just gotta track down this login bug :)

**Comment by DanShu15** [comment]
Ok so this is apparently a known issue with NBT Crafting and other modpacks using REI/NBT have the same problem. Just wanted to update you on it in case anyone else thinks it might have something to do with trader info sent messages in their console :)
Really appreciate the help with the trader :) Thanks again!

**Comment by DanShu15** [comment]
ah one last thing, apparently it is fixed in a hard to find alpha build of NBT at 
https://www.curseforge.com/minecraft/mc-mods/nbt-crafting/files/2934661
:)
