### ISSUE TITLE
Tickspeed a bit high

### ISSUE THREAD

**Issue by DanShu15** [franiscoder/TacoCraft#9]
I hadn't noticed personally yet, but it was reported to me that you can right click on 1 corn plant and harvest an inventory full fairly quickly.
Would it be possible to have harvesting bring it further back in the growth cycle or tone down it's random tickspeed chances?
I'm not sure how that side of it works myself.
We're really loving the mod tho :)

**Comment by frqnny** [comment]
Fixed in 1.3 (future)
